language: java
jdk:
- oraclejdk8

sudo: false
install: true

script:
  - ./webapp/gradlew build
  - cd webapp
  - ./gradlew test
  - ./gradlew war

notifications:
  username:
    recipients:
      - gurao.a@husky.neu.edu
      - subramanian.roh@husky.neu.edu
      - venkatakrishnan.v@husky.neu.edu
