language: java
jdk:
- oraclejdk8

sudo: false
install: true

script:
  - ./webapp/gradlew build
  - cd webapp
  - ./gradlew test
  - ./gradlew war
  - cd build/libs
  - ls -al
  - cd ../../..
  - pwd
  - ls -al

notifications:
  username:
    recipients:
      - gurao.a@husky.neu.edu
      - subramanian.roh@husky.neu.edu
      - venkatakrishnan.v@husky.neu.edu
branches:
  only:
    - assignment_6

after_success:
  - pwd
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - cp infrastructure/aws/codedeploy/*.sh .
  - cp infrastructure/aws/codedeploy/*.yml .
  - zip -r csye-web-app-$TRAVIS_JOB_NUMBER.zip webapp/build/libs/ROOT.war *.sh appspec.yml
  - ls -al
  - mv csye-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: assignment_6
  - provider: codedeploy
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: $s3_bucket
    region: us-east-1
    key: latest/csye-web-app-$TRAVIS_JOB_NUMBER.zip
    bundle_type: zip
    application: $application
    deployment_group: $deployment_group
    wait-until-deployed: true
    after_deploy: "echo 'done deploying!'"
    on:
      branch: assignment_6
