language: java
jdk:
- oraclejdk8

sudo: false
install: true

script:
- ./gradlew war
- ./gradlew build

notifications:
username:
recipients:
-gurao.a@husky.neu.edu
-subramanian.roh@husky.neu.edu
-venkatakrishnan.v@husky.neu.edu
